### ISSUE TITLE
Upcoming Event Form

### ISSUE THREAD

**Issue by Wmaxlees** [amc-ucdenver/website#1]
As a web and server dev, I need to know the form of objects for upcoming events

**Comment by robfitzgerald** [comment]
This created an email and by default reply-to the group is set. (Just
letting you know)

**Comment by Wmaxlees** [comment]
So this will be based on the OrgSync api calls then as well correct?

**Comment by Wmaxlees** [comment]
Also, with the info we get from OrgSync, we will want to add in contributing companies, like Rob mentioned in the contributing companies issue. <https://github.com/amc-ucdenver/website/issues/7>

**Comment by robfitzgerald** [comment]
Should we drop the event database as well, in favor of the orgsync api?

**Comment by Wmaxlees** [comment]
Yeah that's a good idea. We can always add in our own info later if we decide we need to. So, the server will grab the info from orgsync and pass it to the webpage with some cleanup

**Comment by Wmaxlees** [comment]
Closing issue. It is a duplicate at this point of #2.
