### ISSUE TITLE
Company Involvement Form

### ISSUE THREAD

**Issue by Wmaxlees** [amc-ucdenver/website#12]
As a web developer, I need to know where to get the information about how companies can contribute and the form that data will take.

**Comment by robfitzgerald** [comment]
i think that we can make the companies page mostly static.  after all, the point is to come up with prototypical events to sell to them.  so, to answer this question, i think the page may access the events collection for some content for each 'prototype'.  other written content will just be written directly into this page or it's associated directives, such as the 'how to contribute' content.

it would be rad to be able to build a contact us form into this page...  that would require SMTP, something to ask Dat about.

**Comment by Wmaxlees** [comment]
I like the form idea. I added that in when I saw something you wrote in the wiki. I still think it would be nice to add new event types without having to go in and edit the actual code. I was thinking the info could be edited via the officer portal.

**Comment by Wmaxlees** [comment]
Event prototypes Schema as proposed by Rob:

    {
      event: "prototype name",
      image: "image url",
      description: "event description",
      link: "unique id of an event over at orgsync that we can http.get() to add example info"
    }

**Comment by Wmaxlees** [comment]
I would add a list of the different things we need funding for/their help for. For example provide food, host field trip, host mock interviews, provide prize, etc.

**Comment by robfitzgerald** [comment]
is that covered in 'description'?  hmmm
all of this schema content is a wrapper around the case-study-event provided by our orgsync query of 'link'.
description could be a paragraph that speaks to all of the food, field trip, mock inteviews, etc content.
but, we could split it into 2 or more fields ... gonna take a stab at it.

**Comment by robfitzgerald** [comment]
```
{
  event: "prototype name",
  image: "image url",
  description: "event description",
  activities: [ 
    { name: "mock interviews" },
    { name: "watch a scrum meeting" }
  ],
  expenses: [
    { name: "catering" },
    { name: "travel" }
  ], 
  cost: 123456.78,
  link: "unique id of an event over at orgsync that we can http.get() to add example info"
}
```

**Comment by robfitzgerald** [comment]
the only thing we really want for these prototypes from the historical event is a photo, right?  what would we do with the text?  maybe link should be replaced with a url for a photo, and that's it?

**Comment by Wmaxlees** [comment]
Yup. I think that's all perfect. So we're looking at:

```
{
  event: "prototype name",
  image: "image url",
  description: "event description",
  activities: [ 
    { name: "mock interviews" },
    { name: "watch a scrum meeting" }
  ],
  expenses: [
    { name: "catering" },
    { name: "travel" }
  ], 
  cost: 123456.78,
  img: "image address"
}
```

**Comment by robfitzgerald** [comment]
ok, i added it to the Schematics in the wiki.
