### ISSUE TITLE
Contact page - 001

### ISSUE THREAD

**Issue by Wmaxlees** [amc-ucdenver/website#17]
As a user, I would like to see contact information for the officers of ACM on the contact page

**Comment by robfitzgerald** [comment]
AHAHAHAHAHAHHAH
{ "_id" : ObjectId("55920be0bb4c6fe68e9d323d"), "name" : "Max Lees", "position" : "Coffee Runner", "email" : "sk8trb0y1337@aol.com", "photo" : "max.img", "year" : "Grad", "bio" : "<('.'<)" }
{ "_id" : ObjectId("55920be0bb4c6fe68e9d323e"), "name" : "Frodo Baggins", "position" : "Ring Bearer", "email" : "frodo@shire.com", "photo" : "frodo.img", "year" : "Freshman", "bio" : "I threw the ring into the fires of Mount Doom. Now I'm pursuing a degree in CS. Go Lynxs!" }
{ "_id" : ObjectId("55920be0bb4c6fe68e9d323f"), "name" : "JoJo", "position" : "Vice Chair", "email" : "puppylove@gmail.com", "photo" : "frizbee.img", "year" : "Senior", "bio" : "Ruff!" }

**Comment by robfitzgerald** [comment]
:+1:

**Comment by Wmaxlees** [comment]
We merged this out last night, right?
