### ISSUE TITLE
Contact - 002

### ISSUE THREAD

**Issue by Wmaxlees** [amc-ucdenver/website#18]
As a user, I would like to see pictures of current ACM officers so I can easily identify them in person

**Comment by robfitzgerald** [comment]
I didn't get to this really. Or did I? I figured that would have involved writing some specs about image handling somewhere.

**Comment by Wmaxlees** [comment]
This user story is just about seeing the specified images on the web page, which you are doing. There should be a user story at some point for handling images on the server side.
