### ISSUE TITLE
Event Form

### ISSUE THREAD

**Issue by Wmaxlees** [amc-ucdenver/website#2]
As a developer, I would like to know the form of objects containing information about the past events

**Comment by Wmaxlees** [comment]
I'm thinking this should match the upcoming event form so that the website/server can just check the date to see whether to send it or not instead of forcing us to delete the "upcoming event" and then create a new "past event' after the specified day.

**Comment by robfitzgerald** [comment]
totally!

**Comment by robfitzgerald** [comment]
query of event date attribute to decide if it goes in the past events page

**Comment by robfitzgerald** [comment]
i'm addressing the original issue here, given the current idea to write events in orgsync and aggregate to our site using their API.

here's their object:
```
[
  {
    "name": "Test",
    "description": "",
    "umbrella_category": null,
    "location": "There is no location entered for this event.",
    "org_id": 225,
    "is_approved": true,
    "occurrences": [
      {
        "ends_at": "2012-02-22T18:30:00Z",
        "is_all_day": false,
        "starts_at": "2012-02-22T17:30:00Z"
      }
    ],
    "is_public": true,
    "html_description": "",
    "id": 345266,
    "rsvps": 0,
    "category": {
      "name": "Community Service",
      "id": 45
    }
  }
]
```
we can check the ends at date for all results in the return object (an array of event objects), and remove objects in the array that haven't ended before 'today'.  then we have the list of past events.

**Comment by robfitzgerald** [comment]
this has been added to the wiki schematics.

**Comment by Wmaxlees** [comment]
This needs revisiting if we are dropping OrgSync

**Comment by Wmaxlees** [comment]
Okay I changed the name to just plain old "Event Form" because the events will all have the same form and we will just base where they appear by their date tag. 

Draft:

```
{
    "title": "Event Name",
    "date": Date,
    "description": "Description of event",
    "location": "Location of event"
    "rsvp": boolean, // Whether an rsvp is required
    "imgs": [
         {
             "src": "Address of image"
         }
     ]
}
```

Anything else we need?

We can always add in another section later to keep track of rsvps if we decide that's something we want.

```
    "rsvps": [
        {
            "student": "Student Name"
        }
    ]
```

**Comment by robfitzgerald** [comment]
beyond nice-to-have, future features like list of rsvps, comments, and google map API query, i think it's good.

though maybe we can change 'date' to 'eventDate' in case we end up having other date-related entries like createdDate, modifiedDate, etc.

**Comment by Wmaxlees** [comment]
Good call. I'll create some user stories for the extra features and throw this schematic on the wiki with the eventDate adjustment.

**Comment by Wmaxlees** [comment]
I'm actually going to switch eventDate to startDate and add an endDate as well so people can see how long the event will be (ie 2 hours).

**Comment by Wmaxlees** [comment]
Whoops! I'm thinking events. That should be postDate and editDate.

**Comment by robfitzgerald** [comment]
No, this is events not announcements. Start and end makes sense right?
