### ISSUE TITLE
Web Layout

### ISSUE THREAD

**Issue by Wmaxlees** [amc-ucdenver/website#4]
As a web developer, I would like to know the number and general contents of web pages

**Comment by robfitzgerald** [comment]
front facing:

news page - the landing page showing most recently published articles
jobs page - jobs and job details
previous events page - list of previous events and event details
  previous events gallery - popup or page displaying photos of event
companies page - list of types of events to support with examples, pricing, way to contact us
officers page - list of ACM officers past + present
contact page - ways to contact ACM

admin:

login page
password recovery page (depends on a password recovery method...)
edit articles page - CRUD articles collection
edit jobs page - CRUD jobs collection
edit events page - CRUD events collection
edit officers page - CRUD officers collection

...12 pages?

**Comment by robfitzgerald** [comment]
re: news page, how about two sections: a main section for announcements, and a sidebar with a list of upcoming events?

**Comment by Wmaxlees** [comment]
I like that idea. Seems cleaner and easier to read than a feed

**Comment by Wmaxlees** [comment]
For photos of past events, I was thinking it be part of the main previous events page. But it may make more sense have one photo on that page per event and then be able to click on a particular past event and see photos of that event.

**Comment by Wmaxlees** [comment]
I'm a bit curious how you envision the officers page with both past and present officers (maybe separate it by school year?)

**Comment by Wmaxlees** [comment]
Also, I was thinking the contact page and the officer page would be one and the same. What if we did a past officer's page and a current officers page with contact info?

**Comment by robfitzgerald** [comment]
officers active/inactive:

maybe position could be an encoded string, affixed with "active" if they
are active?
or, we can add a boolean to the schema, which would be less work.  let's do
that.

that's a good idea re: officers/contact.  let's do that.

**Comment by robfitzgerald** [comment]
currently discussing this variation in #57 
```
- nav bar w/ pages, admin login (always visible)
all pages front facing:
news page - the landing page showing most recently published articles
jobs page - jobs and job details
previous events page - list of previous events and event details
previous events gallery - popup or page displaying photos of event
companies page - list of types of events to support with examples, pricing, way to contact us
officers/contact page - list of ACM officers past + present; ways to contact ACM
- and when user == admin, arrays of page objects appear as editable text with a submit button
```

**Comment by Wmaxlees** [comment]
I really like the inline idea but what if we just had the admin page be a page we got to separately and log in which creates a cookie. We can then switch over to the actual site and if it detects that cookie, we can CRUD. That way we don't have an admin login on the entire site.

**Comment by robfitzgerald** [comment]
i'm into that.

**Comment by Wmaxlees** [comment]
Okay, decision has been made. A single website with inline CRUD tools for admins.
