### ISSUE TITLE
OrgSync API Key

### ISSUE THREAD

**Issue by Wmaxlees** [amc-ucdenver/website#54]
As a server developer, I will need an orgsync API access key

**Comment by Wmaxlees** [comment]
[OrgSync's](https://orgsync.com/api/docs/v2) relevent information:

Authentication

The first step is to obtain your API Key from your OrgSync Campus Administrator. The API Key is a 40-character string that can be found at the bottom of the Community Settings page. This key must be passed in all API requests via the key parameter. Failing to pass a valid key parameter will result in a 401 Unauthorized status code. You can also authenticate by passing a valid API key in an X-OrgSync-API-Key HTTP header.

Another consideration, that key cannot be in any open source code. Is there some way to hide it?

**Comment by robfitzgerald** [comment]
1) this API doesn't allow you to change data on orgsync.  if this key is
exposed, no data is at risk, as long as announcements do not display
sensitive data.
2) (preferred) we create a setter function to set the API key, and we don't
put it in code.  for each restart of the web service, we need to set the
API key.

**Comment by Wmaxlees** [comment]
Oh, that's a shame. We can't push events onto OrgSync's API?

I'm not sure how #2 works but I say we do that one.

**Comment by robfitzgerald** [comment]
i emailed orgsync to ask about getting an API key.  i couldn't find the mentioned "Community Settings" page.  some org umbrellas (UCD being an umbrella) don't have web APIs enabled.  we'll see...

**Comment by robfitzgerald** [comment]
looks like we need to get in touch with student life.  email reply from orgsync:

>Hi Robert,
>
>Thanks for contacting OrgSync Support!
>
>The API key necessary to run API calls is only visible to the people that run OrgSync on your campus. >With that being said, it doesn’t look like they have the enabled at this time. Please let me know if you >have any questions about this!
>
>Have a good weekend,
>
>Travis Lee
>Customer Support Specialist
>OrgSync, Inc.
>972.907.0900 ext 210 office
>travis@orgsync.com
>www.orgsync.com

**Comment by Wmaxlees** [comment]
No longer needed. OrgSync has been cut out of the equation.
