### ISSUE TITLE
navigation button ids

### ISSUE THREAD

**Issue by robfitzgerald** [amc-ucdenver/website#55]
as a tester, i would like all buttons which trigger http events (get/put and hyperlinks) to have unique ids.

**Comment by Wmaxlees** [comment]
These tester things aren't really discrete chunks of work that we can say are done or not. They span the whole project. I'm gonna put a "Requirements" portion in the wiki and mention all of this. Is that cool?

**Comment by robfitzgerald** [comment]
sure!
