### ISSUE TITLE
Inline vs. Separate Page

### ISSUE THREAD

**Issue by Wmaxlees** [amc-ucdenver/website#57]
As a web dev, I need to know whether we are developing inline administrative tools or if a separate backend will be developed.

**Comment by Wmaxlees** [comment]
Originally posted by Rob:

addressing this: it should be planned for at this stage.
    
i was at first thinking, a whole separate entity.
    
now i'm thinking, much like how these pages allow inline submission...
    
here's my idea.
    
administration is a login popup from the navigation bar at the top of any page. if login is verified, then every entry has an edit button, and there is an add new icon added to the page, which unveils an edit form. submission calls a query to add the document to the collection (add the row to the table) and then the page is reloaded.
sound good?

**Comment by Wmaxlees** [comment]
I moved to a different issue.

My thoughts: That is most definitely easier to use. If we have a lot of people working on the site, however, we will only have a limited amount of pages people can be working on at once. Removing all of the backend pages will reduce that number. I like the idea but maybe we should wait and see how many people want to work on the site before we decide?

**Comment by Wmaxlees** [comment]
On second thought, we have 6 people interested. Assuming half work on server and half on front end there will be plenty of pages for everyone. We should do inline.

**Comment by robfitzgerald** [comment]
the thought to go inline came from working on the directories.  it's going to make for a better user experience if we can make it inline.  but it might get crowded, with multiple people working on the same pages of code.  and of all my ideas today, it's the one i'm least certain of how to implement, though i'm certain it's do-able.

**Comment by Wmaxlees** [comment]
We can do a separate backend first and then if we have time we can implement an inline editor?

**Comment by robfitzgerald** [comment]
problem with that is, they are pretty different implementations.

but the separate backend is probably easier.

maybe this would be a good group discussion, to see what people are interested in.

**Comment by Wmaxlees** [comment]
I actually kinda like the inline option. It will make everything sleeker. If we are going to drop orgsync, we can have options for students to post comments on the different events and everything as well. Obviously a functionality we create much later but it opens up a lot of doors.

**Comment by robfitzgerald** [comment]
if you want comments on events or announcements, we will want to add an array of

```
{
  date: date(),
  subject: "comment subject",
  author: "comment author",
  comment: "comment body"
}
```

to the schema.  that's something we can add in a later version with no impact on the other biz logic discussed thus far.  good thinking for v2.

**Comment by Wmaxlees** [comment]
Beautiful. Well let's ask Jason, but I'm all for dropping orgsync. I will even handle migrating all the users over when it comes time.

P.S. I just realized. There are polls as well though I only used that once. We may want to just take a closer look at orgsync just to make sure we aren't losing anything really important.

**Comment by robfitzgerald** [comment]
we can use google form for our own polls, until you make our "poll" app on our site. ;-)

**Comment by Wmaxlees** [comment]
That sounds good. I'm going to email Jason and get his opinion on dropping OrgSync.

**Comment by Wmaxlees** [comment]
Jason is on board with getting rid of OrgSync entirely.
