### ISSUE TITLE
Production Lifecycle

### ISSUE THREAD

**Issue by Wmaxlees** [amc-ucdenver/website#59]
As a developer, I need to know what the production lifecycle looks like.

**Comment by Wmaxlees** [comment]
Rob could you take a look at [this](https://github.com/amc-ucdenver/website/wiki/Production-Lifecycle) and make sure it's clear? If so this can be closed.

**Comment by robfitzgerald** [comment]
we should probably clarify the terminology we are using locally.  please confirm:
wishlist == issues tab?
user stories == issues?

this might be clearer with more milestones, and matching those milestones to our 2-week sprints (aka naming our sprints with specific team goals via the milestones feature), and associating them with a deployment schedule.  if we are aiming for early august, we pretty much have 4 sprints starting 5/30.  if we can name 4 sprints as stages in our process, and stick a release there at the end (an event on a day we plan to meet and push the repo up to the ~acm site and QA it to confirm it's working) - if we make all those milestones, i feel like this page will be more clear.

an introduction to scrum is good as a reference.

**Comment by Wmaxlees** [comment]
Yeah good clarification.
wishlist == issues tab
user stories == issues

The idea is that at the end of a sprint we are pushing something to release. Here's what I'm thinking if we have 4 sprints:

Sprint 1: Initial Setup/Index Page working
>That means a working server that can accept events and an index page that shows upcoming events and a way for officers to upload event data(we'll add in announcements later)

Sprint 2: Company Page and Announcements
>Add functionality for announcements to the server and index page and add a company portal and CRUD management access for officers + server functionality for company related stuff

Sprint 3: Past Events Page and Officer Page
>All the server, backend, and front facing functionality that goes with these pages

Sprint 4: Jobs Page
>All functionality that goes with this

**Comment by robfitzgerald** [comment]
a few thoughts.
the first sprint will be an onboarding process for the team.  we should have a simpler goal i think, just to flex our muscles on the technologies we have chosen.  

i ran out of time writing this.  i'm not sure i'm right, but, i feel like we should come up with sprints that mirror people's growing knowledge of the technologies.  implementing page y after page x is complete will be an easy step, but it will be a big step to get done with x.  what do you think?

Sprint 1: Onboarding - not a release
sprint 1 test is written, runs, and tests the following in dev:
* loads index page
* calls a hello world angular view
* performs a hello world server request/response.
* performs a query on a trivial database object
* has a responsive css media query for changes in page dimensions

Sprint 2: Skeleton - not a release
sprint 2 test is written, runs, and tests the following in dev:
(i gotta go, but, something like) 
* loads index page (which should be fairly complete)
* loads each angular view (though the view can be empty)
* can query each collection and get an accurate test object returned
* 
...

**Comment by Wmaxlees** [comment]
Maybe it's just me but two weeks for the equivalent of hello world for each dev teams seems really slow. It took me maybe an hour and a half to get my basic node server up and running for advanced. AngularJS hello world will take 20 minutes. I'm not sure about the CSS. I guess we will have to see how much time people are expecting to put in. But if they really want to work on this and have the time even like 3 days for hello world stuff seems generous, right?

On a side note, if we do use that production schedule, it'll be a month and a half (3x2 week sprints) before we have a single usable page. And then 2 weeks to get the entire rest of the site working. If you're really worried it's going to take people that long, we may want to nix this whole idea and just go the easy route.

**Comment by robfitzgerald** [comment]
i'll take another stab at my version and see what form of completed i get to in 4 sprints.  i'm trying to focus on 
* sprint 1 learn the technologies, make mistakes, ask questions, show each technology works.
* sprint 2 all site functionality in place (index page has nav bar, loads views based on menu selection via ngRoute into ngView, database exists and accepts queries, server exists and makes get calls).  all site v1 design choices explored and decided on at this point (email handling, APIs, graphic design outline, fonts, people set on roles)
* sprint 3 complete all views, controllers, services.  have all pages implemented (though not necessarily tested).  assess: is there time to add features?
* sprint 4 v1 site deploy.  fully tested site.

**Comment by Wmaxlees** [comment]
If you want to do something like that, I'm okay with that. But that is the Waterfall method which is the antithesis of Agile.

**Comment by robfitzgerald** [comment]
Ya that's true. I wasn't thinking about that and was just thinking about
aligning our plan with our primary goal of learning.
But I would like to give true agile a shot here, as part of that learning.
Let's do something more like what you wrote.

**Comment by Wmaxlees** [comment]
We can always do a week or two of straight learning and then start the agile workflow afterward if you think people will need it. It may be a good idea to wait and see how much time people are expecting to put in?

**Comment by robfitzgerald** [comment]
Ya. I feel like our situation differs from a typical ongoing agile project
in that our first goal isn't associated with the delivery of any product.
Perhaps we should explicitly name that here. Once we are all in and ready
to code, we can switch into agile. And, if people are moving faster than
our planning, we can pull stories back from sprint 2 and give them
something to do. Which is definitely a part of agile. Tangentially: because
of this, our sprints shouldn't share the name or gist of any particular
user story because they can move around.

We can always do a week or two of straight learning and then start the
agile workflow afterward if you think people will need it. It may be a good
idea to wait and see how much time people are expecting to put in?

—
Reply to this email directly or view it on GitHub
<https://github.com/amc-ucdenver/website/issues/59#issuecomment-105245755>.

**Comment by Wmaxlees** [comment]
How I've seen it work is people generally take on more than they can handle and then roll things they don't finish over to the next sprint. But either way, whether we're adding in more user stories or rolling over to the next sprint, the outcome seems the same. So I'm okay either way with this.

As far as sprint contents, here's what I'm thinking:
   It's true our first sprint goal may be learning but after that, I think we should stick to the agile ideal of having a new functionality deliverable by the end. I'm not sure the name matters that much but the idea is that we are focusing on delivering either one or a set of user stories.
   There needs to be some structure as well. We can't just have people picking user stories they want to work on and completing those. That would mean a total miss-match between functionality of server and website.
   To that end, once we decide a user story belongs in a sprint, it should be a very rare case to remove it. If they have to roll over, that's fine. We can't guarantee something can be done in a set amount of time. But once we decide on functionality, we should complete it.

Thoughts?

**Comment by robfitzgerald** [comment]
my project lead at work thinks that it's better form and better agile to choose less and pull new stories back if people run out of work.  that way you are making a clearer goal each sprint and meeting it, versus if we constantly fail to complete our work.  i personally feel we could go either way, let's just be consistent.
and i agree with the rest of your points, let's be clear about our goals and it's nbd about naming the sprints.  should we take a swing now at building a few sprints over in issues:milestones?

**Comment by Wmaxlees** [comment]
Okay, well your project lead certainly has more experience so let's do it that way. I'm thinking we just pick the bare minimum for a piece of functionality then and add additional features via user stories as people complete their work? Let me take a stab at it in the milestones and see what you think. I'll share a link once I've got it complete.

**Comment by Wmaxlees** [comment]
Alright, here's a really simple [sprint](https://github.com/amc-ucdenver/website/wiki/Officer-Information#boards?repos=36133794&milestone=Alpha-2015-06-20T06:00:00Z) that I think would actually be perfect for the first real sprint. It doesn't have much functionality yet but it's gonna require a lot of backend work to get it up and running so there will be plenty of work to do. And it leaves plenty of space to add in more user stories if people have time.

**Comment by robfitzgerald** [comment]
nope, that's not a sprint, that's the officer information schema.  but [this guy](https://github.com/amc-ucdenver/website/milestones/Alpha) is your sprint, and i think it will be a good start.  this will include making the following happen:
* configure dev environment for http over web
* node server with handlers for the [event object](https://github.com/amc-ucdenver/website/wiki/Event-Schema) [API](https://github.com/amc-ucdenver/website/wiki/REST-Calls#events)
* index.html calls the angular module into a div with ng-view which uses our app.routes.js file to find the event.html view and load it into the ng-view on index.html
* event.html has a directive to display events
* event.html has a service to call the node event API
* we have applied our schema via mongoose to our mongodb database
* create some filler documents in the database for event objects
* write tests for all of the above in protractor(/mocha?) as acceptance criteria for user stories
* along with everyone doing their work in the [technology resources](https://github.com/amc-ucdenver/website/wiki/Technology-Resources) section of the wiki.

**Comment by robfitzgerald** [comment]
we could skip implementing routes and just hardwire the view into event.html - probably a good idea in sprint 1.

**Comment by Wmaxlees** [comment]
Okay so lemme make sure we're on the same page here.

We want to meet everyone on Saturday of this week if they are available. We will get everyone caught up on what the site will be and how this will all work and then divvy up the work.

The following week (that is, week 1), we will not have a sprint but give everyone time to explore the technologies they will be using for their portion of the project. We meet again on Saturday to get everyone's feedback and see if we're ready to continue.

Week 2, if everyone feels comfortable, we begin the 'alpha' sprint to get the framework built and the index page working based on the bullet points you noted above. 

From there, we can develop sprints based on how 'alpha' went?

**Comment by robfitzgerald** [comment]
sounds great!

whenever the next email goes out, let's clearly state these objectives for our use of people's time: 8 hours of coding/week, a 1-2 hour meeting every other week (currently saturday noonish), and a quick check in every weekday via a forum ('no work done today' to 'this is what i did:...').

let's word it that we want people to join on next saturday if they can.  if they can't make it saturday, we will come up with a role for them, and they should expect to learn technologies next week.
