### ISSUE TITLE
Job Listing Content

### ISSUE THREAD

**Issue by Wmaxlees** [amc-ucdenver/website#6]
As a content manager, I need to know where the job listings will come from

**Comment by robfitzgerald** [comment]
i suggest a collection called jobs, and an admin page that has CRUD access to that collection.
something like this for the schema:
```
{
  title: "job title",
  company: "company name",
  link: "url",
  posted_date: new Date('today'),
  description: "short description",
  closed: boolean
}
```

**Comment by robfitzgerald** [comment]
closed (default false==null) is whether or not the job is closed.  maybe/maybe not a good idea.  pros: keep a permanent list of all posted jobs ever but disable/grey out the closed ones.  cons: more upkeep on our side.  for that reason, maybe one more attribute, a closed_date: Date(), and the server can track that closed state (creates a task for a node.js script that checks all closed dates at midnight and sets closed=true for any that will change).

**Comment by Wmaxlees** [comment]
Hmm, closed dates a good idea. Will we always have access to that sort of information, though? The job board in general is going to require a lot of upkeep on our part in contacting companies to get this information

**Comment by robfitzgerald** [comment]
it could be not there by default.  the code could look for it, and if it's not there or null, then the operation isn't performed.

**Comment by robfitzgerald** [comment]
then we're like, ho crap, that job listing has been there for forever and stuff.  then we manually go in and change it.

**Comment by Wmaxlees** [comment]
Sounds good. I'm thinking the job listing page should probably be one of the last pieces we implement on the site, though.

**Comment by robfitzgerald** [comment]
good idea

**Comment by Wmaxlees** [comment]
Another idea to think about: Should the job listing auto delete after it has been closed? Or do we want to keep a listing of old jobs

**Comment by Wmaxlees** [comment]
Also, the original post was intended to figure out where we're actually getting job opening information. Not how we will pass the information around. Are we soliciting companies for this info or scouring job boards or what? Maybe another api to monster or indeed is available? Do we want to put in that effort?

**Comment by robfitzgerald** [comment]
um, well, i feel like jobs get passed to us often.  this should be a place
for that, for unique finds.  people can search monster/indeed/whatevs on
their own time.

i think we should hold on to job listings and just grey them out when they
close.  i would like to show a record of value that the ACM site adds, and
i think this is one solid way.

**Comment by Wmaxlees** [comment]
Okay, sounds good to me
