### ISSUE TITLE
Pictures

### ISSUE THREAD

**Issue by Wmaxlees** [amc-ucdenver/website#9]
As a web developer, I need to know where the pictures from past events will be kept and how to access them.

**Comment by robfitzgerald** [comment]
it seems we could either manually FTP our photos to the site into separate event directories, and store the URL as a string in our events collection... or we can use GridFS in MongoDB and store the files in the collection.
this may be a research task.  images should also definitely be associated with title, date, and tag(s) fields somewhere.

**Comment by Wmaxlees** [comment]
Well I know there is no need to ftp them. We can load files onto the server using Angular. I'm going to put this as an enhancement though. Doesn't seem like it will be that important to get the site started.

I'm thinking ultimately we want to store the pictures in the database but let's start out by just storing a link coupled with the event id that the image belongs to. Something like

```
{
    "caption": "An image caption",
    "event": "123456"
    "src": "Image location"
}
```

Eventually: [this](http://blog.mongodb.org/post/183689081/storing-large-objects-and-files-in-mongodb)

**Comment by robfitzgerald** [comment]
yea, GridFS.  it's just wether or not we want to deal with making a web interface for batch image file storage, or if it's easier to FTP them into somewhere like img/gallery/event_directory_name and then run a script to integrate them from there.

i like the "as for now" solution.  and i'm assuming these image objects live inside an array in an event object, assuming we are building our own event database locally.

**Comment by Wmaxlees** [comment]
Ahh yeah that's a good idea. Have the event own the image, basically. So instead of an event id for each image, the image needs an id and the event just keeps a list of those ids.

For simplicities sake, we may for now just want to have the event keep an array of image source urls and implement the caption later as an enhancement when we add in database support.

**Comment by robfitzgerald** [comment]
Good idea. And that will be easy, where the schema change won't impact
other logic.

**Comment by Wmaxlees** [comment]
Okay, so for now, no image database schemas. The image information will all be contained within the event form.
